### ISSUE TITLE
Pixel font support

### ISSUE THREAD

**Issue by prime31** [rds1983/SpriteFontPlus#10]
Is there any way to get pixel fonts crisp with SpriteFontPlus? It seems to apply some sort of smoothing when generating the textures. Is there some way to use point filtering?

**Comment by rds1983** [comment]
Does the smoothing appear in both SpriteFont(created in runtime from ttf) and DynamicSpriteFont? Or only in the latter?
As SpriteFontPlus uses [C# port of stb_truetype](https://github.com/rds1983/SpriteFontPlus/tree/master/src/SpriteFontPlus/StbTrueType) to rasterize ttfs. DynamicSpriteFont also uses [C# port of fontstash](https://github.com/rds1983/SpriteFontPlus/tree/master/src/SpriteFontPlus/FontStashSharp) to dynamically render character glyphs on atlas.
So if smoothing appears in both SpriteFont and DynamicSpriteFont then it is stb_truetype problem, which is unlikely easy to fix.
If it appears only in DynamicSpriteFont, then it is fontstash problem that is much easier to fix.

**Comment by prime31** [comment]
I am seeing it in both. I guess I’ll stick to good old bitmap fonts for now where I can control the aliasing/filtering completely. Thanks for the great lib!

**Comment by rds1983** [comment]
I've enhanced SpriteFontPlus with the ability to create SpriteFont from AngelCode BMFont. Maybe it will solve the issue.

**Comment by prime31** [comment]
Thanks! Bitmap fonts are exactly what I was using. They work like a champ since you can control the output image completely.
