### ISSUE TITLE
[BMFont] Read texture file names from fnt file

### ISSUE THREAD

**Issue by augustozanellato** [rds1983/SpriteFontPlus#13]
SpriteFontPlus should read the image file names from the fnt file instead of relying on the developer to pass in a Texture2D

**Comment by rds1983** [comment]
Good point.
I plan to add following method to the BMFontLoader in the future version:
```c#
public static SpriteFont LoadXml(string xml, Func<string, Texture2D> textureGetter);
```
BMFontLoader would call textureGetter with the image file name as parameter and expect texture to be returned.

**Comment by augustozanellato** [comment]
That would be perfect for the project I'm working on at the moment

**Comment by rds1983** [comment]
Unfortunately SpriteFont supports only one texture.
So above task isn't simple. As it would require combining all textures into one, updating character glyph positions on it.

**Comment by augustozanellato** [comment]
I think that you could at the moment just implement it for a single texture.
Regarding the combination of the textures you could use getData and setData with an offset on a single big texture, then with the same offset you edit the glyphs position

**Comment by rds1983** [comment]
I've changed BMFontLoader.LoadSignature to the above.
For now it supports only single texture.
