### ISSUE TITLE
Feature Request: UTF-32 Support

### ISSUE THREAD

**Issue by rds1983** [rds1983/SpriteFontPlus#2]
http://community.monogame.net/t/spritefontplus/11271/4?u=rds1983

**Comment by rds1983** [comment]
You want those changes to be merged into SpriteFontPlus?
If yes, can you make a PR?

**Comment by willmotil** [comment]
It is your project i leave you to decide what to take or leave. 
That spritebuffer isn't really suitable for anything but superficial testing.

**Comment by rds1983** [comment]
> One other thing i couldn't seem to get the vertical position to line the letters up to the baseline.
> Do you know how to do that ?

No, sorry.

**Comment by rds1983** [comment]
I've added UTF-32 Support to DynamicSpriteFont. This sample demonstrates it in action: https://github.com/rds1983/SpriteFontPlus/tree/master/samples/SpriteFontPlus.Samples.DynamicSpriteFont
![image](https://user-images.githubusercontent.com/1057289/51784468-a259d100-217b-11e9-8113-d42e952ac2d1.png)
