### ISSUE TITLE
FontStashSharp.Font should use GCHandle to make a stable longlived memory address to _data 

### ISSUE THREAD

**Issue by bartwe** [rds1983/SpriteFontPlus#30]
Currently FromMemory uses 'fixed' to get a pointer to the data to initialize the font, however stbtt requires this pointer to remain valid for the duration of usage of the font. This requires using a longlives GCHandle.Alloc(_data, GCHandleType.Pinned)

**Comment by rds1983** [comment]
Cool, thanks for noticing this. Maybe this is reason of #20.

**Comment by rds1983** [comment]
After some thought I decided that this issue is better to be fixed at StbTrueTypeSharp side and created the corresonding issue: https://github.com/StbSharp/StbTrueTypeSharp/issues/2

**Comment by rds1983** [comment]
After even more thought I've made safe version of StbTrueTypeSharp and moved SpriteFontPlus on top of it.
