### ISSUE TITLE
Colors per glyph with DrawString

### ISSUE THREAD

**Issue by charles-esterbrook** [rds1983/SpriteFontPlus#31]
In addition to a call like this:
```cs
spriteBatch.DrawString(font, "The quick brown fox", positionVector, Color.White);
```

I would like to provide the colors for each glyph:
```cs
spriteBatch.DrawString(font, "The quick brown fox", positionVector, colors);
```

Where `colors` is an array of Color the same length or longer than the number of glyphs that will be rendered.

This would allow highlighting words in text, without needing bold, italics, etc. Messages like "Press [Space] to continue" could have the "[Space]" portion highlighted (presumably in the game's color scheme).

Is there a way to do something like this now?

If not, would this be possible as a feature request?

**Comment by rds1983** [comment]
There isnt a way to do this now.
However it's cool and easy-to-make feature request.

**Comment by charles-esterbrook** [comment]
Thanks
