### ISSUE TITLE
Why do you use reflection here?

### ISSUE THREAD

**Issue by bladecoder** [rds1983/SpriteFontPlus#32]
Hi,

I ha a problem porting this project to Switch because of this code in `TtfFontBakerResult.cs`:

```
 var constructorInfo = typeof(SpriteFont).GetTypeInfo().DeclaredConstructors.First();
var font = (SpriteFont)constructorInfo.Invoke(new object[]
{
        texture, glyphBounds, cropping,
        chars, (int)FontFontPixelHeight, 0, kerning, ' '
});
```

Probably the error I am having is my fault, but I was wondering why are you using reflection here instead of:

```
var font = new SpriteFont(texture, glyphBounds, cropping, chars, (int)FontFontPixelHeight, 0, kerning, ' ');
```

Best Regards!

**Comment by rds1983** [comment]
Hello,
This code is used for both MonoGame and FNA versions. And latter SpriteFont constructor isnt public unfortunately.
Btw, I think some already ported SFF to Switch: https://github.com/bartwe/SpriteFontPlus
Though it lacks ordinary SpriteFont support. However it has some additional features.
As well replacement of DynamicSpriteFont Dictionary with more performant Int32Map.

**Comment by bladecoder** [comment]
Hi,

I created a version that works on Switch just creating the Size.cs class so I can delete the dependency from System.Core.Drawing and changing the reflection call for `new`.

Here: https://github.com/bladecoder/SpriteFontPlus

Thanks!
