### ISSUE TITLE
DynamicSpriteFont overlaps the previous glyph slightly when adding a new glyph to the atlas.

### ISSUE THREAD

**Issue by alkalinethunder** [rds1983/SpriteFontPlus#42]
Hey there.  I recently forked SpriteFontPlus to make it work with my game's custom rendering system.  I'm probably going to make a PR since it'll allow people to use `DynamicSpriteFont` without needing to use `SpriteBatch` if they're like me and are writing their own batcher.  But during testing, I noticed that my game was rendering weird artifacts.  Like part of another character's glyph drawing where it shouldn't be.  Here's an example of what I mean.

![image](https://user-images.githubusercontent.com/31224503/89485196-3e4f9a00-d76e-11ea-859f-ae3618c0061c.png)

Have a look at the "t" at the end of "affect", and the "t" in "the" right after it.  See that faint gray line? That looks like part of another glyph got rendered right at the left edge of "t" right?  Well, upon looking at what my custom renderer was getting as a `sourceRect`, I noticed that there was an off-by-one error in the `Left` field.  Here's what I mean.

Let's say I'm drawing "abc" on screen for the first time.  For brevity, the font is mono-space and each glyph is 8 units wide and 14 units tall.

 - DynamicSpriteFont sees "a" and notices that the glyph isn't in the underlying texture atlas yet.  It sees that the atlas is empty and will draw the glyph at (0,0) in the atlas.  The glyph's texture bounds are (0, 0, 8, 14).
 - Now it's going to draw "b".  It sees that "b" is not in the atlas yet, and so will add it.  Because "a" was previously added at (0, 0) and was 8 units wide, "b" will be added right next to it at (8, 0).  **This is the bug.**

Some characters, like "l" or "h" or "M" may have pixels that get rendered right at the edge of what will become their texture bounds.  They may be translucent but are, nonetheless, still there.  Since glyphs are overlapping like this, alpha blending will kick in and part of the previous glyph will be sampled into the new glyph.  To fix this, I would render the new glyph at the previous glyph's position + previous glyph's width + 1.  So, if the previous glyph is at (0, 0) and 8 units wide, the new glyph will be placed at (9, 0).

I can fix this myself in my fork and incorporate it into my PR, but I'm not entirely sure where this calculation is done and how, so I'll need some pointers on where to look.

**Comment by rds1983** [comment]
I merged that PR, but then reverted it since it made an allocation every DrawString call that used SpriteBatch. 
I couldn't figure out an elegant way how to integrate it without every draw allocations.
