### ISSUE TITLE
Blurry Fonts

### ISSUE THREAD

**Issue by aragubas** [rds1983/SpriteFontPlus#47]
Hi, I'm making a PNGTuber app with Monogame, since this is an app and not a game I need flexible text rendering so I choose SpriteFontPlus... but all the fonts looks blurry!

I have a content manager that loads fonts into a list so I can call GetFont(FontName, FontSize) to get a font from cache, would that affect the font quality?

here's the code of the method that bake fonts
```
public static SpriteFont BakeFont(string fontName, int size) {
  string fontPath = Path.Combine(DefaultContentPath, "Fonts", fontName + ".ttf");
  if (fontPath.EndsWith(".ttf.ttf")) fontPath.Replace(".ttf.ttf", ".ttf");
  
  TtfFontBakerResult fontBakeResult = TtfFontBaker.Bake(File.ReadAllBytes(fontPath),
    size, 1024, 1024, new[] {
      CharacterRange.BasicLatin,
      CharacterRange.Latin1Supplement,
      CharacterRange.LatinExtendedA,
      CharacterRange.Cyrillic
    });

  return fontBakeResult.CreateSpriteFont(LiVerseApp.Graphics!.GraphicsDevice);
}

```

![image](https://user-images.githubusercontent.com/47148297/234148191-5f4c1929-a9f5-4e68-a599-b366873a17c6.png)

the fonts in this image are: NotoSans (for the small text) and Ubuntu (for the big text) I downloaded them from GoogleFonts
am I doing something wrong here or is there something wrong with SpriteFontPlus

**Comment by aragubas** [comment]
ah I forgot to mention but the size of the font in the small text is 18px, and 28px in the bigger text

**Comment by rds1983** [comment]
Seems to be issue with stb_truetype(which is used to rasterize glyphs).
I'd recommend try to load fonts from Angelcode BMFont.

**Comment by aragubas** [comment]
Update: I managed to fix the problem by changing the sampler state to PointClamp, the default is LinearClamp x3

I'll close this issue

![image](https://github.com/rds1983/SpriteFontPlus/assets/47148297/fd503eb9-d4fe-478f-a998-73dc831a9380)
