### ISSUE TITLE
Add GetYOffset() to DynamicSpriteFont

### ISSUE THREAD

**Issue by Apostolique** [rds1983/SpriteFontPlus#5]
Add `GetYOffset()` to DynamicSpriteFont and remove `var yOff = font.Ascent * scale;` from the `DrawString` method.

https://github.com/rds1983/SpriteFontPlus/blob/master/src/SpriteFontPlus/DynamicSpriteFont.cs#L84

I need my string to be drawn exactly at the position I give. With GetYOffset, we can manually add it back if needed.

**Comment by rds1983** [comment]
Thing is the underlying text rendering engine sometimes draws string a few pixels lower than provided y coord.
I've added following method to the DynamicSpriteFont:
```c#
public Rectangle GetTextBounds(Vector2 position, string text);
```
According to my testing it provides accurate results.
![image](https://user-images.githubusercontent.com/1057289/51796122-9aec0380-221f-11e9-92da-9faa3f72bce5.png)

**Comment by rds1983** [comment]
btw, new version(0.6.0.6) with that fix is available on the nuget.

**Comment by rds1983** [comment]
After more fiddling around, I've managed to fix MeasureString. Now it simply returns bigger heights:
![image](https://user-images.githubusercontent.com/1057289/51796323-6c235c80-2222-11e9-8c8c-22beb77e92c7.png)

**Comment by rds1983** [comment]
Above fix is at the nuget too. Version 0.6.0.7.
